// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQH1_yGCMB3TFgnqVfy_y6oN2aQFAZJA',
    appId: '1:32540899377:web:011b0b8ed5f6a839ccbd10',
    messagingSenderId: '32540899377',
    projectId: 'taxi-tigui-403912',
    authDomain: 'taxi-tigui-403912.firebaseapp.com',
    databaseURL: 'https://taxi-tigui-403912-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-tigui-403912.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBON78B38FvuDvWYI4fXtQMaCNXYhT3fbQ',
    appId: '1:32540899377:android:715c68545bebee51ccbd10',
    messagingSenderId: '32540899377',
    projectId: 'taxi-tigui-403912',
    databaseURL: 'https://taxi-tigui-403912-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-tigui-403912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTM-_pN17SgGG5mxfnlM8k7PLbGGlsZSg',
    appId: '1:32540899377:ios:4995459be9430d33ccbd10',
    messagingSenderId: '32540899377',
    projectId: 'taxi-tigui-403912',
    databaseURL: 'https://taxi-tigui-403912-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-tigui-403912.appspot.com',
    iosBundleId: 'com.example.dashboard1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTM-_pN17SgGG5mxfnlM8k7PLbGGlsZSg',
    appId: '1:32540899377:ios:9fbf91d67a04c205ccbd10',
    messagingSenderId: '32540899377',
    projectId: 'taxi-tigui-403912',
    databaseURL: 'https://taxi-tigui-403912-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-tigui-403912.appspot.com',
    iosBundleId: 'com.example.dashboard1.RunnerTests',
  );
}
